sourcegraph/go-vcs

vcs/gitcmd/repo.go, vcs/hg/repo.go, vcs/repository_test.go
Work in progress PR to close #37, see there for context.
Currently only added failing testcases.
=> gitcmd: Fix ResolveRevision failing to return vcs.ErrRevisionNotFound on valid-looking revisions.

.travis.yml, Makefile, README.md, vcs/git/clone_update.go
- Mention that both `libssh2` and `libgcrypt` are hard prerequisites for
libgit2 implementation in advance of its installation.
- The Makefile "install" target was outdated (missing the `git checkout
next` step). In addition to that, it repeats the exact same steps as
described in Resolving Dependencies section, which is assumed to be
done by the time user gets to Installing section. I removed it since
it's unneeded and may cause confusion.
- Closes #43.
=> Improve git installation process.

README.md, cmd/go-vcs/go-vcs.go, vcs/git/repo.go, vcs/gitcmd/repo.go, vcs/hg/repo.go, vcs/hgcmd/repo.go, vcs/repository.go, vcs/repository_test.go, vcs/ssh_test.go, vcs/testing/mock_repository.go
This is a breaking API change for `Branches` method of `Repository` interface. As any breaking API change, it is not done lightly, but needs to be done in order to support additional features for `Branches` method call. By using an options struct, future enhancements and pagination support will not incur additional API breakage.
- It changes the signature of `Branches` to be more like `Commits`, which accepts an `Options` struct where parameters may be specified that describe details of the `Branches` query.
- ~~It also adds a `total uint` return value, which will always be the total number of branches, even if fewer are returned (due to pagination, for example). Note that there is no pagination support at this time, but since it's likely to be added in the future, it's hopefully better …
=> Add BranchesOptions for Repository.Branches method, support getting behind/ahead counts.

README.md, vcs/gitcmd/repo.go, vcs/repository.go, vcs/repository_test.go, vcs/vcs.pb.go, vcs/vcs.proto
When calling vcs.Branches method, it is now possible to set IncludeCommit option to true. Doing so will include full commit details for each returned branch (i.e., the head commit for each branch).
=> Add optional commit details to vcs.Branch.

README.md, cmd/go-vcs/go-vcs.go, vcs/gitcmd/repo.go, vcs/repository.go, vcs/repository_test.go
- This is done by allowing to select only commits that modify a given path.
- The direction of this commit is largely based on research and findings from commit 2a71007acc73d25867c6e9e6a0e706b346b7336c. See it and its commit message for rationale.
- Minor fixes to ./cmd/go-vcs and improvements to code style consistency.
This is ready for initial review. /cc @sqs I may want to do some minor fixups and add tests tomorrow.
=> Add support for file/dir history.

vcs/gitcmd/repo.go
When there is a match in a binary file, the output of `git grep` does not much
what we expect, leading to a slice bounds out of range in
`gitcmd.(*Repository).Search`. The format of a binary match line is
Binary file HASH:PATH/TO/BINARY/FILE matches
=> vcs/gitcmd: Ignore binary files for Search

vcs/gitcmd/repo.go
Previously, getting a single commit would always count all commits on that tree, which is expensive and slow. The result was immediately discarded.
I initially tried to add a `calculateTotal bool` parameter, but then I thought I'd try a `total *uint64` as input/output instead. It's probably not the greatest, but it is internal code (not public API) and slightly less redundant. I'm okay with changing it if requested.
=> gitcmd: Don't count all commits unless needed.

vcs/git/repo.go, vcs/gitcmd/repo.go, vcs/hg/repo.go, vcs/hgcmd/repo.go, vcs/internal/path.go, vcs/util/path.go
This change handles root paths (i.e. `/foo`) as if they were relative
(`foo`) such that asking the VFS for a file at the root works properly.
Without this change it is impossible to use the VFS provided with:
`golang.org/x/tools/godoc/vfs/httpfs`
As `net/http.FileSystem` will implicitly convert all URL paths into
absolute paths at the root of the FS.
Additionally this makes the behavior of the VFS backends comply with
the OS VFS implementation provided by the `godoc/vfs` package.
Fixes #23
=> vcs/*: fix handling of root paths inside VFS backends

vcs/git/clone_update.go, vcs/git/repo.go
This updates the usage of git2go to account for recent API changes in the `next` branch.
Fixes the Travis-ci build.
=> vcs/git: update for recent changes to git2go

vcs/git/repo.go
This results in both git backends to produce same ordering in Commits method.
Fixes #56.
=> git: Use reverse chronological order in Commits method.

vcs/git/repo.go, vcs/gitcmd/repo.go, vcs/hg/repo.go, vcs/hgcmd/repo.go, vcs/repository.go
This is an alternative implementation of the potential performance improvement proposed in #58. This time it's a non-breaking API change, adding a field that lets users not interested in `total` to opt out of calculating it.
Closes #58 because it offers the same functionality addition, done through a different API (non-breaking).
=> Add CommitsOptions.NoTotal field to avoid calculating total.

vcs/gitcmd/repo.go, vcs/repository_test.go, vcs/vcs.pb.go, vcs/vcs.proto
This corresponds to running `git branch --contains {commit-id}`
=> add ContainsCommit option for listing branches containing a commit to gitcmd

vcs/gitcmd/repo.go
There are only 2 callers of `lsTree` in this package. Both of them already acquire and hold the `fs.repoEditLock.RLock()` when calling `lsTree`.
Remove `lsTree` doing a double lock and document it as requiring caller to hold the lock.
=> gitcmd: Avoid lsTree doing a double lock.

vcs/git/clone_update.go, vcs/git/repo.go, vcs/ssh_test.go
Resolves #60.
This PR updates the API. However, it doesn't work now because there seems to be an issue in latest git2go on next branch with Clone method, see https://github.com/libgit2/git2go/commit/4b9cbd78fd266767f6bdf55257c4ee2b1611bbe0#commitcomment-11919367. **Edit:** I've made https://github.com/libgit2/git2go/issues/217 to track that issue.
Until that is resolved, this PR will fail.
=> Update git2go API.

vcs/git/repo.go
Followup to #61. This was added to master after, and unfortunately I missed it. This fixes Travis build.
=> git: Update git2go API (another instance).

vcs/ssh_test.go
This reverts commit 9c3be6693258f5dfe68403c5f885d9dd6537491f.
Issue https://github.com/libgit2/git2go/issues/218 has been resolved and these tests should pass now.
It's a follow up to https://github.com/sourcegraph/go-vcs/pull/61#issuecomment-123152613 (/cc @slimsag).
=> Revert skipping git2go ssh tests since upstream issue resolved.

vcs/gitcmd/repo.go
The `if opt.SSH != nil {` guard was there twice, which is harmless, but unnecessary. Remove it, which simplifies the code.
=> Remove double if guard.

README.md, cmd/go-vcs/go-vcs.go, vcs/gitcmd/repo.go, vcs/hgcmd/repo.go, vcs/repository.go, vcs/testing/mock_repository.go, vcs/vcs.pb.go, vcs/vcs.proto
Added method Repository.Committers() to fetch the committers list in a git repo using `git shortlog -sne {rev}` command. The information returned for each committer consists of: name, email, # of commits in the specified branch/revision.
This method is only implemented for `gitcmd`; a mercurial implementation is pending.
=> Fetch list of committers in a repository

vcs/gitcmd/repo.go, vcs/remote.go
Use a git pass helper via `GIT_ASKPASS` env var (https://www.kernel.org/pub/software/scm/git/docs/gitcredentials.html) to provide password to git commands.
=> Add HTTPSConfig to RemoteOpts, ability to provide password.

.travis.yml, vcs/diff_test.go, vcs/gitcmd/repo.go, vcs/hg/repo.go, vcs/hgcmd/repo.go, vcs/internal/script.go, vcs/repository_test.go, vcs/search_test.go, vcs/ssh/server_test.go
- replaced "git rev-parse SPEC^{commit}" with short-hand "git rev-parse SPEC^0" because {} has a special meaning in Windows
- git client expects path arguments to use slashes, so forcing them
- ssh expects path to key file (-i KEY) to use slashes (checked with Cygwin's git and MSYS's git)
- forcing using slashes instead of OS-specific file separator
- making OS-specific GIT_SSH and GIT_ASKPASS helpers (bat files on Windows vs shell scripts on Unix)
- fixed some unit tests (actually everything but "native git" work now on Windows)
- os.Chmod is platform-independent while os.File.Chmod is not implemented on Windows
- On Windows, commit hash may differ when there are symlinks made by different tool (Cygwin/Msys/...) thus computing proper hash before test (affects unit tests)
- code …
=> Windows support 

vcs/gitcmd/repo.go, vcs/internal/script.go, vcs/internal/script_test.go
We avoid the need to do unix/batch escaping entirely by just outputting the file
in the script.
=> gitcmd: Correctly escape passwords

README.md, cmd/go-vcs/go-vcs.go, vcs/git/clone_update.go, vcs/gitcmd/remote_update_parser.go, vcs/gitcmd/remote_update_parser_test.go, vcs/gitcmd/repo.go, vcs/hgcmd/repo.go, vcs/remote.go, vcs/repository_test.go, vcs/ssh_test.go
This is an early draft of a sample implementation for proposal #79. It's very easy to refactor and change it.
- Currently implemented in gitcmd backend only, the new functionality parses the output of `git remote update` operation and returns it to the caller.
- This is a breaking API change because it adds an extra return parameter to a method of RemoteUpdater interface.
- Add tests for the parser.
Resolves #79.
=> Add UpdateResult to UpdateEverything method.

vcs/gitcmd/repo.go
Prior to this change we would not use the `--prune` flag which removes
any remote-tracking references that no longer exist on the remote after
updating.
In our app, this caused mirrored repositories updated via `UpdateEverything`
to have branches that cannot ever be deleted (by deleting the branch from
remote).
=> vcs/gitcmd: use 'git remote update --prune' option

vcs/util/tracer/repository.go, vcs/util/tracer/tracer.go, vcs/util/tracer/vfs.go
This change adds a utility package which records VCS operations to an `*appdash.Recorder`
by wrapping a `vcs.Repository` value. It implements the optional interface types
that a `vcs.Repository` implementation may opt-in to, so no functionality is
lost. Because it works at the interface level we can trace all different
backends (`gitcmd`, `git`, `hg`, etc) without writing new tracing code.
In Appdash, all events are prefixed with `vcs.Type` for easier filtering:
=> vcs/util/tracer: add a utility package for recording VCS operations to Appdash

vcs/util/tracer/gitcmd.go, vcs/util/tracer/tracer.go
This fixes the last failing test on CI for our main repo so that [we can merge support for tracing git operations](https://src.sourcegraph.com/sourcegraph/.changes/372).
Note: this is a follow-up to https://github.com/sourcegraph/go-vcs/pull/85
=> vcs/util/tracer: fix CrossRepoDiffer in gitcmd backend

vcs/gitcmd/repo.go
or else the new one will not take effect if there is a prior one in play.
This was discovered to be incorrect as part of a [separate / unrelated change](https://src.sourcegraph.com/sourcegraph/.commits/597229995ed0bd8f5e89915cb4cdeb25caa87eb3), but nonetheless was incorrect code.
=> vcs/gitcmd: unset GIT_ASKPASS prior to appension

vcs/git/vfs.go
This allows working with repositories where submodules are not initialized, or the backend doesn't support fetching submodule details.
=> vcs/git: Make it not a fatal error when git submodule is missing details (URL).

README.md
Point to the `vcs.Repository` interface, since that's a better starting point for this project than the root directory (i.e. https://sourcegraph.com/github.com/sourcegraph/go-vcs).
Thanks to @prashantv for reporting the issue.
=> README: Fix broken links.

vcs/git/vfs.go, vcs/gitcmd/repo.go, vcs/hg/repo.go, vcs/hgcmd/repo.go, vcs/util/tracer/vfs.go
It is needed to continue to implement the [`vfs.FileSystem`](https://godoc.org/golang.org/x/tools/godoc/vfs#FileSystem) interface after golang/tools@16d1af8d88c08b6a22e07a0900aad5279a7fb4fd.
Fixes #100.
=> all: Add RootType method to vfs.FileSystem implementations.

vcs/gitcmd/repo.go
The `--` separator is optional, but always providing it helps avoid arguments being ambiguous in some situations.
Below is an example of when the base branch does not exist.
Before:
exec `git log` failed: exit status 128. Output was:
fatal: ambiguous argument 'notexist': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
After:
exec `git log` failed: exit status 128. Output was:
fatal: bad revision 'notexist'
The new error is better because we can map it to `vcs.ErrCommitNotFound` rather than a generic unknown error type. This will be done in next PR.
=> vcs/gitcmd: Always provide -- separator.

.travis.yml, vcs/gitcmd/repo.go, vcs/repository.go, vcs/repository_test.go
[`vcs.CommitsOptions`](https://godoc.org/sourcegraph.com/sourcegraph/go-vcs/vcs#CommitsOptions) has Head and Base fields, documented as:
https://github.com/sourcegraph/go-vcs/blob/d5c79b0b071fb52ee773641c60cfdce93c5f80d0/vcs/repository.go#L128-L129
The Base field is documented to produce results equivalent to `git log Base..Head`. However, that was not the case, the previous code produced results equivalent to `git log Head...Base` instead.
In many cases, those two are equivalent, which is likely why it has gone unnoticed (and the previous tests didn't catch this).
Add more thorough test coverage to catch the subtle difference.
=> vcs/gitcmd: Use correct commit range in commitLog.

vcs/repository_test.go
Due to issue #104, most of hg tests were skipped in PR #103. This change skips the remaining few hg tests. As a result, `./vcs` package tests can pass without hg binary installed.
When issue #104 is resolved, all of the hg tests can be reinstated.
Updates PR #103.
Updates issue #104.
=> Skip remaining few hg tests.

vcs/git/repo.go, vcs/gitcmd/repo.go, vcs/repository_test.go
There was inconsistency in how annotated tags were handled by various git backends (git, gitcmd) and various methods (`ResolveRevision`, `ResolveTag`, `Tags`). In some cases, annotated tags were dereferenced, and in other cases, they were not. This is issue #24.
This PR fixes the inconsistency by opting to always dereference annotated tags to the underlying commit ID.
It consists of two _logical_ commits (please don't squash them, otherwise information will be lost):
1. First commit adds tests that cover the inconsistent annotated tag behavior, without changing the implementation. The tests demonstrate the inconsistent behavior, and are passing.
2. Second commit changes `git` and `gitcmd` behavior to always dereference annotated tags, and updates tests to have consistent output. The tests …
=> Fix inconsistency in annotated tag dereferencing; add test coverage for it.

cmd/go-vcs/go-vcs.go, vcs/hgcmd/repo.go
It has changed in https://github.com/sourcegraph/go-diff/pull/30.
Updates https://github.com/sourcegraph/go-diff/issues/27
/cc @sqs
~~You should probably not merge this before https://github.com/sourcegraph/go-diff/issues/33 is resolved, otherwise this PR will break this project in module mode.~~ **Edit:** Issue https://github.com/sourcegraph/go-diff/issues/33 has been resolved, so this is safe to merge now.
=> cmd/go-vcs, vcs/hgcmd: update .../sourcegraph/go-diff/diff import path
